[package]
name = "nuvende-campanha5"
version = "0.1.0"
edition = "2018"


[dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
tokio = { version = "1", features = ["full"] }
sysinfo = "0.24"
serde_json = "1.0"

